name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution
  push:
    branches:
      - master # Runs on every push to the master branch

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Ensures the workflow has access to the repo

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-light.svg?color_snake=#F34B7D&color_dots=#EBEDF0,#9AE8A8,#40C463,#30A14E,#216E39
            dist/snake-dark.svg?color_snake=#F34B7D&color_dots=#171A22,#0F4428,#006D32,#27A640,#39D353

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
